### ISSUE TITLE
你好，你在github中上传的mamt3d代码是公司临时公开的，现在已经关闭，请您快速关闭，或联系我，李先生 18633267120

### ISSUE THREAD

**Issue by einstein20050430** [baian1/mul_pages_demo#7]
你好，你在github中上传的mamt3d代码是公司临时公开的，现在已经关闭，请您快速关闭，或联系我，李先生 18633267120

**Comment by baian1** [comment]
ok

**Comment by baian1** [comment]
代码库删掉了

**Comment by einstein20050430** [comment]
你好，非常感谢您的响应，另外两个从您库中转载的，如果您有好的办法，也帮我通知他们。
现在我们正在想各种方法通知，有了您的帮助，会事半功倍。


https://github.com/sproutcui/Mamt3D
https://github.com/cxw-github/Mamt3D


再一次感谢！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "baian1/mul_pages_demo"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月24日(星期六) 晚上11:50
收件人:&nbsp;"baian1/mul_pages_demo"<mul_pages_demo@noreply.github.com&gt;;
抄送:&nbsp;"再度梦想"<59135929@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [baian1/mul_pages_demo] 你好，你在github中上传的mamt3d代码是公司临时公开的，现在已经关闭，请您快速关闭，或联系我，李先生 18633267120 (#7)





 
Closed #7.
